labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true

steps:
  build:
    image: python
    commands:
      - python -m pip install hatchling hatch-vcs build
      - python -m build
    when:
      event: tag
  
  publish:
    image: gitea.elara.ws/music-kraken/plugin-twine
    settings:
      username: __token__
      password:
        from_secret: pypi_token
    when:
      event: tag
      
  release:
    image: woodpeckerci/plugin-release
    settings:
      title: "Version ${CI_COMMIT_TAG}"
      files:
        - 'dist/hisscl-*.whl'
        - 'dist/hisscl-*.tar.gz'
      api_key:
        from_secret: gitea_token
    when:
      event: tag